//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW01_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string PlayerSurname { get; set; }
        public string PlayerAge { get; set; }
        public decimal PlayerAverage { get; set; }
        public Nullable<int> TeamID { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
